# Configurações de build para a Netlify
[build]
  # Comando para construir o site
  command = "yarn build"
  # Diretório onde os arquivos do site construído são salvos
  publish = "dist"

# Regra de redirecionamento para Single Page Applications (SPA)
# Isso garante que o roteamento do lado do cliente funcione corretamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
